# ===== Spring Boot Application Name =====
spring.application.name=FlightBooking

# ===== Database Configuration =====
spring.datasource.url=jdbc:postgresql://localhost:5432/flightbooking
spring.datasource.username=postgres
spring.datasource.password=Divinah 40.
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / Hibernate Configuration =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# ===== Server Port Configuration =====
server.port=8088
server.address=0.0.0.0

# ===== Email Configuration (Gmail SMTP) =====
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=divinahoenga4@gmail.com
spring.mail.password=ehpw qbnk usfk vfzj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Optional: Email Encoding
spring.mail.default-encoding=UTF-8
